### ISSUE TITLE
Encoders tick upward while robot is sitting still

### ISSUE THREAD

**Issue by FTC18035** [Pedro-Pathing/Documentation#7]
I followed the steps to set up the loacalizer. We are running two wheel odometry with the IMU in the chub. I tried running the forward localization tuner and the numbers just started climbing on their own. I do not know what could be causing this. Sorry to be messaging this close to Christmas but our next meeting is the 28th. (Saturday after Christmas) if you guys don't reply in time it's no problem. Enjoy your Christmas. Merry Christmas

**Comment by BaronClaps** [comment]
Join the discord, where I can better help you. [Discord Link](https://discord.gg/VdXcfyrB)

**Comment by FTC18035** [comment]
I messaged you on the discord and you linked me to the website

**Comment by BaronClaps** [comment]
Oh, just make a new post dry
